FROM kalilinux/kali-rolling

# korea 
RUN echo "deb http://mirror.siwoo.org/kali kali-rolling main non-free contrib" > /etc/apt/sources.list
RUN apt update && apt install -y \
    net-tools python3 python3-pip \
    apt-transport-https \
    ca-certificates \
    openssh-server openssh-client \
    curl whatweb seclists openvpn \
    dnsutils \
    whois \
    exploitdb \
    hydra \
    iputils-ping openvpn\
    nmap \
    tmux \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && chmod 755 msfinstall && ./msfinstall

RUN wget https://github.com/yudai/gotty/releases/download/v1.0.1/gotty_linux_amd64.tar.gz \
    && tar -xvf gotty_linux_amd64.tar.gz \
    && chmod +x gotty \
    && mv gotty /usr/local/bin/ \
    && rm gotty_linux_amd64.tar.gz

# 컨테이너 시작 시 Gotty를 통해 bash를 실행 (포트 8080에서 터미널 공유)
CMD ["gotty", "-w", "-p", "8080", "bash"]